language: ruby
rvm:
- 2.3.0
before_script:
- cp config/database.sample.yml config/database.yml
- psql -c 'create role hub SUPERUSER LOGIN;' postgres
- psql -c 'create database hub_api_test;' -U hub postgres
script: bundle exec rake db:migrate && bundle exec rspec spec
services:
- redis-server
deploy:
  provider: script
  script: bin/deploy.sh
